@startuml
skinparam usecase {
BackgroundColor AliceBlue
BorderColor MidnightBlue
ArrowColor Salmon
}

left to right direction

utilisateur #AliceBlue;line:MidnightBlue;line.bold;text:Black
administrateur #AliceBlue;line:MidnightBlue;line.bold;text:Black
utilisateur <.right. administrateur : extends
rectangle "Ransomtion Protecware" {
  :utilisateur: -- (Changer langue)
  (Login) .up.> (Changer langue) : include
  :utilisateur: -- (Voir l'historique des ransomwares bloqués)
  (Login) .up.> (Voir l'historique des ransomwares bloqués) : include
  :utilisateur: -- (Changer couleur)
  (Login) .up.> (Changer couleur) : include
  :utilisateur: -- (Restaurer un backup)
  (Login) .up.> (Restaurer un backup) : include
  (Restaurer un backup) <.down. (Backup hebdomadaire) : include
  :administrateur: -- (Activer/Desactiver le logiciel)
  (Login) .up.> (Activer/Desactiver le logiciel) : include
  usecase UC1 as "Relancer logiciel bloqué
  --
  **Extension points**
  Ajouter à la whitelist
  "
  (Ajouter à la whitelist) <.down. UC1 : extends
  (Login) .up.> (Ajouter à la whitelist) : include
  :administrateur: -- (Ajouter à la whitelist)

  (Détecter l'éxécution d'un ransomware) .left.> (Coupure des interfaces réseaux) : include
  (Détecter l'éxécution d'un ransomware) .left.> (Arrêt du programme concerné) : include
  (Détecter l'éxécution d'un ransomware) .left.> (Tentative de déchiffrement) : include
  usecase UC2 as "Restaurer une sauvegarde
  --
  **Extension points**
  Tentative de déchiffrement
  "
  (Tentative de déchiffrement) <.down. UC2 : extends: tentative échouée


}
@enduml