
languages = {

    "english": {
        "restore_label": "Select a backup\n to restore",
        "backup": "Backups",
        "restore": "Restore",
        "file": "File",
        "theme": "Theme",
        "language": "Language",
        "hide": "Hide",
        "colors": "Colors",
        "black&white": "Black and White",
        "password": "Password : ",
        "login": "Login : ",
        "path": "Path : ",
        "name": "Name : ",
        "whitelist": "\nWhitelist\n",
        "load": "Loading...",
        "start": "Start",
        "shutdown": "Shutdown",
        "add": "Add",
        "del": "Delete",
        "blocked": "Number of blocked malwares",
        "history": "Blocked softwares\n",
        "addHist": "Whitelist",
        "active": "Software is active...",
        "inactive": "Software is inactive!",
        "quit": "Are you sure you want to quit ?",
        "yes": "Yes",
        "no": "No",
        "error_already": "Already in whitelist",
        "soft_info": "Information about the software",
        "validate": "Validate",
        "cancel": "Cancel",
        "authenticate": "Authentication needed"
    },

    "french": {
        "restore_label": "Selectionnez une sauvegarde\n à restaurer",
        "backup": "Sauvegardes",
        "restore": "Restaurer",
        "file": "Fichier",
        "theme": "Thème",
        "language": "Langue",
        "hide": "Masquer",
        "colors": "Couleurs",
        "black&white": "Noir et Blanc",
        "password": "Mot de Passe : ",
        "login": "Identifiant : ",
        "path": "Chemin : ",
        "name": "Nom : ",
        "whitelist": "\nWhitelist\n",
        "load": "Chargement...",
        "start": "Allumer",
        "shutdown": "éteindre",
        "add": "Ajouter",
        "del": "Supprimer",
        "blocked": "Nombre de malwares bloqués",
        "history": "Logiciels bloqués\n",
        "addHist": "Whitelister",
        "active": "Logiciel actif...",
        "inactive": "Logiciel inactif !",
        "quit": "Êtes vous sûr de vouloir quitter ?",
        "yes": "Oui",
        "no": "Non",
        "error_already": "Déjà dans la whitelist",
        "soft_info": "Informations du logiciel",
        "validate": "Valider",
        "cancel": "Annuler",
        "authenticate": "Authentification nécessaire"
    }
}
